name: Release

on:
  workflow_run:
    workflows: ['Test']
    types: [completed]
    branches: 
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Log masks
        run: echo "::add-mask::$NAME_MASK"

      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: parse-version
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./publish.js');
            await script({github, context});
          result-encoding: string

      - name: Build Windows
        run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-windows-gnu

      - name: Build Linux
        run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-linux-gnu

      - name: Create release
        run: |
          gh release create --generate-notes \
            "${{steps.parse-version.outputs.result}}" \
            "./zig-out/bin/drivercom-gui" \
            "./zig-out/bin/drivercom-gui.exe" \
            "./zig-out/bin/drivercom-gui.pdb"

