name: Release

on:
  workflow_run:
    workflows: ['Test']
    types: [completed]
    branches: 
      - main
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Log masks
        run: echo "::add-mask::$NAME_MASK"

      - uses: actions/checkout@v4

      - name: Build Windows
        run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-windows-gnu

      - name: Build Linux
        run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-linux-gnu

      - uses: actions/github-script@v7
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./publish.js');
            await script({github, context});
