name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Linux]
    runs-on: [self-hosted, "${{ matrix.os }}" ]
    steps:
      - name: Log masks
        run: echo "::add-mask::$NAME_MASK"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Install dependencies
        run: deno i --frozen

      - name: Prepare `styled-system`
        run: deno task prepare

      - name: Run `deno fmt`
        if: matrix.os == 'self-hosted'
        run: deno fmt --check

      - name: Run `deno lint`
        if: matrix.os == 'self-hosted'
        run: deno lint

      - name: Run `tsc`
        if: matrix.os == 'self-hosted'
        run: tsc
