name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Linux]
    runs-on: [self-hosted, "${{ matrix.os }}"]
    steps:
      - name: Log masks on Linux
        if: matrix.os == 'Linux'
        run: echo "::add-mask::$NAME_MASK"

      - name: Log masks on Windows
        if: matrix.os == 'Windows'
        run: echo "::add-mask::$env:NAME_MASK"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Check formatting
        run: bun run fmt-check

      - name: Check lints and types
        run: bun run check

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cargo Verify Project
        working-directory: ./src-tauri
        run: cargo verify-project

      - name: Cargo Format
        working-directory: ./src-tauri
        run: cargo fmt --check

      - name: Cargo Build
        run: bun run tauri build --verbose
        env:
          GH_TOKEN: ${{ secrets.DRIVERCOM_CLI_RELEASE_ACCESS_TOKEN }}

      - name: Cargo Test
        working-directory: ./src-tauri
        run: cargo test --verbose

      - name: Cargo Clippy
        working-directory: ./src-tauri
        run: cargo clippy --no-deps -- -W clippy::pedantic
